/**
 * The campaign orchestrator: campaign = playbook + audience + schedule.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THIS REPLACES
 *
 * `ai-enhanced-communication.controller.ts:batchGenerateCommunications` is a
 * `for (const patientId of patientIds)` loop that calls the single-generate
 * handler once per patient — inside the HTTP request, sequentially, with a
 * fabricated `res` object and a `batchId: \`batch-${Date.now()}\`` that is
 * written nowhere. Fifty patients is fifty sequential model calls in one
 * request; nothing survives a restart, nothing can be resumed, and "how did
 * that batch go?" has no answer.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * GENERATION GOES THROUGH THE PLAYBOOK RUNTIME, NOT AROUND IT
 *
 * Every recipient is generated by `PlaybookRuntime.run()` — the same call
 * `POST /v1/outreach/trigger` makes for a single event. That is the whole design
 * of this file, and the reason is uniformity: the approval policy, the
 * compliance gate, quiet hours, per-recipient throttles and the channel plan all
 * apply per message, exactly as they do for a one-off send.
 *
 * A campaign path that assembled its own messages would be a second engine with
 * a second set of bugs — and the first thing it would quietly skip is the
 * unsubscribe check, on the one send shape where volume makes that expensive.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * HOW A CAMPAIGN TARGETS ITS OWN PLAYBOOK, WITHOUT AN ENGINE CHANGE
 *
 * `OutreachTrigger` has no "run this playbook" field, and the matcher selects on
 * trigger type, event type and a `where` predicate over the payload. The obvious
 * move — add `playbookKey` to the trigger and filter on it — would edit
 * `src/engine/playbooks/`, which P11's exit criterion forbids, and that
 * criterion exists precisely to catch a shortcut like it.
 *
 * So targeting uses the mechanism already there. The orchestrator puts
 * `campaignPlaybookKey` in the payload; a campaign-capable playbook declares
 *
 *   { "type": "campaign", "where": { "campaignPlaybookKey": { "eq": "lead.followup" } } }
 *
 * and the existing bounded predicate does the selection. One campaign runs one
 * playbook, the rule is readable in the pack file rather than inferred from
 * code, and the engine did not have to learn what a campaign is.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * RESUMABILITY, AND WHY IT IS TWO STATE MACHINES
 *
 * `message_batches.status` is the batch's state (DRAFT→QUEUED→PROCESSING→
 * COMPLETED|CANCELLED — the source's own vocabulary, kept). `campaign_recipients
 * .status` is each recipient's. Relaunching processes only rows still PENDING,
 * so an interrupted campaign resumes rather than restarts, and nobody is
 * messaged twice because they were row 900 of 1,000 when the pod died.
 *
 * The belt to that braces is the trigger's idempotency key,
 * `campaign:<campaignId>:<recipientId>`: `playbook_runs` has a unique index on
 * (tenant, playbook, idempotency_key), so even a double-processed recipient
 * produces one run and one send (0007).
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT `cancel` CAN AND CANNOT DO — READ THIS BEFORE TRUSTING IT
 *
 * Cancel stops generation immediately and cancels every recipient that has not
 * been generated yet. It does **not** recall messages already handed to the
 * queue: `NotificationQueue` exposes `enqueue`, `enqueueMany`, `stats` and
 * `close`, and nothing that removes a job.
 *
 * Adding removal would mean changing the delivery plane, and P11's exit
 * criterion is that no file under `src/engine/{playbooks,content,approvals,
 * compliance,delivery}` changes — that constraint is what proves the engine was
 * already general enough. So the limit is documented rather than designed
 * around, and it is recorded as a gap. In practice the exposure is small: a
 * recipient is enqueued only after it has been generated, so cancelling a
 * 10,000-recipient campaign that is 200 in leaves 9,800 ungenerated and at most
 * a few in flight.
 */
import { and, eq, sql, type SQL } from 'drizzle-orm';
import type { Logger } from 'winston';

import type { Db } from '../../db/index.js';
import {
  campaignRecipients,
  campaigns,
  messageBatches,
  messages,
  messageAnalytics,
  playbooks,
} from '../../db/schema.js';
import { ConflictError, NotFoundError, ValidationError } from '../../platform/http/errors.js';
import { tenantWhere, type TenantScope } from '../../platform/db/tenant-scope.js';
import type { PlaybookRuntime } from '../playbooks/runtime.js';
import type { OutreachTrigger, PlaybookRunResult } from '../playbooks/trigger.js';
import type { AudienceService } from './audience.service.js';

/** Batch states, and they are the source's own (0001's CHECK). */
export const CAMPAIGN_STATUSES = [
  'DRAFT',
  'QUEUED',
  'PROCESSING',
  'PAUSED',
  'COMPLETED',
  'CANCELLED',
] as const;
export type CampaignStatus = (typeof CAMPAIGN_STATUSES)[number];

/**
 * Per-recipient states. `PENDING` is the only one the run loop picks up, which
 * is what makes a relaunch a resume.
 */
export const RECIPIENT_STATUSES = [
  'PENDING',
  'PENDING_APPROVAL',
  'QUEUED',
  'SENT',
  'SUPPRESSED',
  'SKIPPED',
  'FAILED',
  'CANCELLED',
] as const;
export type CampaignRecipientStatus = (typeof RECIPIENT_STATUSES)[number];

export interface CampaignInput {
  name: string;
  description?: string;
  type?: string;
  playbookKey: string;
  audienceId: string;
  senderId?: string;
  /** Merged into every recipient's trigger payload, before their own context. */
  context?: Record<string, unknown>;
  schedule?: { sendAt?: string };
  metadata?: Record<string, unknown>;
}

export interface CampaignStats {
  campaignId: string;
  status: CampaignStatus;
  total: number;
  byStatus: Record<string, number>;
  sent: number;
  delivered: number;
  opened: number;
  clicked: number;
  replied: number;
  suppressed: number;
  failed: number;
}

export interface OrchestratorDeps {
  db: Db;
  logger: Logger;
  runtime: PlaybookRuntime;
  audiences: AudienceService;
  /** Bounded fan-out. Model providers rate-limit; so does this. */
  concurrency?: number;
}

const DEFAULT_CONCURRENCY = 5;

export class CampaignOrchestrator {
  constructor(private readonly deps: OrchestratorDeps) {}

  async create(scope: TenantScope, input: CampaignInput): Promise<{ id: string }> {
    const playbook = await this.playbookByKey(scope, input.playbookKey);
    await this.deps.audiences.require(scope, input.audienceId);

    const [row] = await this.deps.db
      .insert(campaigns)
      .values({
        tenantId: scope.tenantId,
        subTenantId: scope.subTenantId ?? null,
        name: input.name,
        description: input.description,
        type: input.type ?? 'PLAYBOOK',
        status: 'DRAFT',
        playbookId: playbook.id,
        audienceId: input.audienceId,
        senderId: input.senderId,
        schedule: input.schedule ?? {},
        metadata: { ...(input.metadata ?? {}), context: input.context ?? {} },
      })
      .returning({ id: campaigns.id });

    return { id: row!.id };
  }

  async getById(scope: TenantScope, id: string) {
    const [row] = await this.deps.db
      .select()
      .from(campaigns)
      .where(and(tenantWhere(campaigns, scope), eq(campaigns.id, id)))
      .limit(1);
    return row ?? null;
  }

  async require(scope: TenantScope, id: string) {
    const found = await this.getById(scope, id);
    if (!found) throw new NotFoundError(`Campaign '${id}' not found for this tenant`);
    return found;
  }

  async list(scope: TenantScope) {
    return this.deps.db
      .select()
      .from(campaigns)
      .where(tenantWhere(campaigns, scope))
      .orderBy(sql`${campaigns.createdAt} DESC`);
  }

  /**
   * Expand the audience, then process. Returns as soon as the expansion is
   * recorded — the run loop is awaited by the caller only in tests, because a
   * 10,000-recipient campaign must not be an HTTP request that times out.
   */
  async launch(
    scope: TenantScope,
    campaignId: string,
    options: { await?: boolean } = {},
  ): Promise<{ expanded: number; batchId: string }> {
    const campaign = await this.require(scope, campaignId);

    if (campaign.status === 'PROCESSING') {
      throw new ConflictError(`Campaign '${campaignId}' is already running`);
    }
    if (campaign.status === 'COMPLETED' || campaign.status === 'CANCELLED') {
      throw new ConflictError(
        `Campaign '${campaignId}' is ${campaign.status} and cannot be launched again`,
      );
    }
    if (!campaign.audienceId) {
      throw new ValidationError('A campaign needs an audience before it can be launched');
    }

    const batchId = await this.openBatch(scope, campaign.id, campaign.name);
    const expanded = await this.expand(scope, campaign.id, campaign.audienceId);

    await this.setStatus(scope, campaign.id, 'PROCESSING');
    await this.deps.db
      .update(messageBatches)
      .set({ status: 'PROCESSING', eventCount: expanded, updatedAt: new Date() })
      .where(and(tenantWhere(messageBatches, scope), eq(messageBatches.id, batchId)));

    const run = this.process(scope, campaign.id, batchId);
    if (options.await) await run;
    else void run.catch((error) => this.deps.logger.error('campaign run failed', { error }));

    return { expanded, batchId };
  }

  async pause(scope: TenantScope, campaignId: string): Promise<void> {
    const campaign = await this.require(scope, campaignId);
    if (campaign.status !== 'PROCESSING' && campaign.status !== 'QUEUED') {
      throw new ConflictError(`Campaign '${campaignId}' is ${campaign.status}, not running`);
    }
    await this.setStatus(scope, campaignId, 'PAUSED');
  }

  async resume(scope: TenantScope, campaignId: string, options: { await?: boolean } = {}) {
    const campaign = await this.require(scope, campaignId);
    if (campaign.status !== 'PAUSED') {
      throw new ConflictError(`Campaign '${campaignId}' is ${campaign.status}, not paused`);
    }
    await this.setStatus(scope, campaignId, 'PROCESSING');

    const batchId = await this.currentBatch(scope, campaignId);
    const run = this.process(scope, campaignId, batchId);
    if (options.await) await run;
    else void run.catch((error) => this.deps.logger.error('campaign resume failed', { error }));
  }

  /**
   * Stop generating, and cancel everyone not yet generated. Messages already
   * handed to the queue are NOT recalled — see the header.
   */
  async cancel(scope: TenantScope, campaignId: string): Promise<{ cancelled: number }> {
    const campaign = await this.require(scope, campaignId);
    if (campaign.status === 'COMPLETED') {
      throw new ConflictError(`Campaign '${campaignId}' has already completed`);
    }

    await this.setStatus(scope, campaignId, 'CANCELLED');

    const cancelled = await this.deps.db
      .update(campaignRecipients)
      .set({ status: 'CANCELLED', updatedAt: new Date() })
      .where(
        and(
          tenantWhere(campaignRecipients, scope),
          eq(campaignRecipients.campaignId, campaignId),
          eq(campaignRecipients.status, 'PENDING'),
        ),
      )
      .returning({ id: campaignRecipients.id });

    const batchId = await this.currentBatch(scope, campaignId).catch(() => null);
    if (batchId) {
      await this.deps.db
        .update(messageBatches)
        .set({ status: 'CANCELLED', completedAt: new Date(), updatedAt: new Date() })
        .where(and(tenantWhere(messageBatches, scope), eq(messageBatches.id, batchId)));
    }

    this.deps.logger.info('campaign cancelled', {
      tenantId: scope.tenantId,
      campaignId,
      cancelledBeforeGeneration: cancelled.length,
    });
    return { cancelled: cancelled.length };
  }

  async stats(scope: TenantScope, campaignId: string): Promise<CampaignStats> {
    const campaign = await this.require(scope, campaignId);

    const byStatusRows = await this.deps.db
      .select({ status: campaignRecipients.status, value: sql<number>`count(*)::int` })
      .from(campaignRecipients)
      .where(
        and(
          tenantWhere(campaignRecipients, scope),
          eq(campaignRecipients.campaignId, campaignId),
        ),
      )
      .groupBy(campaignRecipients.status);

    const byStatus: Record<string, number> = {};
    for (const row of byStatusRows) byStatus[row.status] = row.value;

    // Engagement joins through the message the recipient produced. Delivery
    // receipts arrive via the P8 webhooks and land on message_analytics, one
    // row per message (0008), so these counts cannot double.
    const [engagement] = await this.deps.db
      .select({
        delivered: sql<number>`count(*) FILTER (WHERE ${messages.deliveredAt} IS NOT NULL)::int`,
        opened: sql<number>`count(*) FILTER (WHERE ${messageAnalytics.openedAt} IS NOT NULL)::int`,
        clicked: sql<number>`count(*) FILTER (WHERE ${messageAnalytics.clickedAt} IS NOT NULL)::int`,
        replied: sql<number>`count(*) FILTER (WHERE ${messageAnalytics.repliedAt} IS NOT NULL)::int`,
      })
      .from(campaignRecipients)
      .innerJoin(messages, eq(messages.id, campaignRecipients.messageId))
      .leftJoin(messageAnalytics, eq(messageAnalytics.messageId, messages.id))
      .where(
        and(
          tenantWhere(campaignRecipients, scope),
          eq(campaignRecipients.campaignId, campaignId),
        ),
      );

    const total = Object.values(byStatus).reduce((a, b) => a + b, 0);
    return {
      campaignId,
      status: campaign.status as CampaignStatus,
      total,
      byStatus,
      sent: byStatus.SENT ?? 0,
      delivered: engagement?.delivered ?? 0,
      opened: engagement?.opened ?? 0,
      clicked: engagement?.clicked ?? 0,
      replied: engagement?.replied ?? 0,
      suppressed: byStatus.SUPPRESSED ?? 0,
      failed: byStatus.FAILED ?? 0,
    };
  }

  async recipients(
    scope: TenantScope,
    campaignId: string,
    options: { status?: string; limit?: number; offset?: number } = {},
  ) {
    const clauses: SQL[] = [
      tenantWhere(campaignRecipients, scope),
      eq(campaignRecipients.campaignId, campaignId),
    ];
    if (options.status) clauses.push(eq(campaignRecipients.status, options.status));

    return this.deps.db
      .select({
        id: campaignRecipients.id,
        recipientId: campaignRecipients.recipientId,
        status: campaignRecipients.status,
        messageId: campaignRecipients.messageId,
        error: campaignRecipients.error,
        sentAt: campaignRecipients.sentAt,
      })
      .from(campaignRecipients)
      .where(and(...clauses))
      .orderBy(campaignRecipients.createdAt)
      .limit(Math.min(options.limit ?? 100, 500))
      .offset(options.offset ?? 0);
  }

  // ── internals ─────────────────────────────────────────────────────────────

  /** Audience → campaign_recipients. Idempotent, so a relaunch adds newcomers. */
  private async expand(
    scope: TenantScope,
    campaignId: string,
    audienceId: string,
  ): Promise<number> {
    const memberIds = await this.deps.audiences.memberIds(scope, audienceId);
    if (memberIds.length === 0) return 0;

    const existing = await this.deps.db
      .select({ recipientId: campaignRecipients.recipientId })
      .from(campaignRecipients)
      .where(
        and(
          tenantWhere(campaignRecipients, scope),
          eq(campaignRecipients.campaignId, campaignId),
        ),
      );
    const seen = new Set(existing.map((e) => e.recipientId));
    const fresh = memberIds.filter((id) => !seen.has(id));
    if (fresh.length === 0) return 0;

    for (let i = 0; i < fresh.length; i += 500) {
      await this.deps.db.insert(campaignRecipients).values(
        fresh.slice(i, i + 500).map((recipientId) => ({
          tenantId: scope.tenantId,
          campaignId,
          recipientId,
          status: 'PENDING' as const,
        })),
      );
    }
    return fresh.length;
  }

  /**
   * The run loop. Reads PENDING recipients in pages and generates them with
   * bounded concurrency, re-checking the campaign's status between pages so a
   * pause or a cancel takes effect within one page rather than at the end.
   */
  private async process(scope: TenantScope, campaignId: string, batchId: string): Promise<void> {
    const campaign = await this.require(scope, campaignId);
    const concurrency = Math.max(1, this.deps.concurrency ?? DEFAULT_CONCURRENCY);
    const context = ((campaign.metadata as Record<string, unknown> | null)?.context ??
      {}) as Record<string, unknown>;

    const [playbook] = await this.deps.db
      .select({ key: playbooks.key })
      .from(playbooks)
      .where(and(tenantWhere(playbooks, scope), eq(playbooks.id, campaign.playbookId!)))
      .limit(1);
    if (!playbook) throw new NotFoundError('The campaign references a playbook that is gone');

    let succeeded = 0;
    let failed = 0;

    for (;;) {
      const live = await this.require(scope, campaignId);
      if (live.status !== 'PROCESSING') break;

      const page = await this.deps.db
        .select({ id: campaignRecipients.id, recipientId: campaignRecipients.recipientId })
        .from(campaignRecipients)
        .where(
          and(
            tenantWhere(campaignRecipients, scope),
            eq(campaignRecipients.campaignId, campaignId),
            eq(campaignRecipients.status, 'PENDING'),
          ),
        )
        .orderBy(campaignRecipients.createdAt)
        .limit(concurrency * 10);

      if (page.length === 0) break;

      for (let i = 0; i < page.length; i += concurrency) {
        const slice = page.slice(i, i + concurrency);
        const outcomes = await Promise.all(
          slice.map((row) =>
            this.generateOne(scope, campaign.id, playbook.key, context, row, campaign.senderId),
          ),
        );
        for (const ok of outcomes) {
          if (ok) succeeded += 1;
          else failed += 1;
        }
      }
    }

    const remaining = await this.countPending(scope, campaignId);
    const finalStatus = await this.require(scope, campaignId);

    if (remaining === 0 && finalStatus.status === 'PROCESSING') {
      await this.setStatus(scope, campaignId, 'COMPLETED');
      await this.deps.db
        .update(messageBatches)
        .set({
          status: 'COMPLETED',
          successCount: succeeded,
          failureCount: failed,
          completedAt: new Date(),
          updatedAt: new Date(),
        })
        .where(and(tenantWhere(messageBatches, scope), eq(messageBatches.id, batchId)));
    } else {
      await this.deps.db
        .update(messageBatches)
        .set({ successCount: succeeded, failureCount: failed, updatedAt: new Date() })
        .where(and(tenantWhere(messageBatches, scope), eq(messageBatches.id, batchId)));
    }
  }

  /** One recipient, through the same runtime a single event uses. */
  private async generateOne(
    scope: TenantScope,
    campaignId: string,
    playbookKey: string,
    context: Record<string, unknown>,
    row: { id: string; recipientId: string | null },
    senderId: string | null,
  ): Promise<boolean> {
    if (!row.recipientId) {
      await this.settle(scope, row.id, 'FAILED', { error: 'the row has no recipient' });
      return false;
    }

    const trigger: OutreachTrigger = {
      type: 'campaign',
      tenantId: scope.tenantId,
      subTenantId: scope.subTenantId,
      // Two different consumers read two different levels of this payload, and
      // conflating them renders an empty template:
      //   - the MATCHER evaluates its `where` predicate against the payload
      //     ROOT, so `campaignPlaybookKey` lives there (see the header);
      //   - the RENDERER's `context` namespace comes from `payload.context`
      //     (runtime.ts:298), so the campaign's own context goes under that key.
      payload: {
        campaignId,
        campaignPlaybookKey: playbookKey,
        context,
      },
      correlationId: `campaign:${campaignId}`,
      // (tenant, playbook, key) is unique in playbook_runs (0007), so a
      // reprocessed recipient produces one run and one send, not two.
      idempotencyKey: `campaign:${campaignId}:${row.recipientId}`,
      recipientId: row.recipientId,
      ...(senderId ? { senderId } : {}),
    };

    try {
      const results = await this.deps.runtime.run(trigger);
      const result = results.find((r) => r.playbookKey === playbookKey) ?? results[0];
      if (!result) {
        await this.settle(scope, row.id, 'SKIPPED', { error: 'no playbook matched' });
        return false;
      }
      await this.settle(scope, row.id, mapStatus(result), {
        messageId: result.messageIds[0],
        error: result.reason ?? result.contractErrors?.join('; '),
      });
      return result.status !== 'FAILED';
    } catch (error) {
      await this.settle(scope, row.id, 'FAILED', {
        error: error instanceof Error ? error.message : 'generation threw',
      });
      return false;
    }
  }

  private async settle(
    scope: TenantScope,
    id: string,
    status: CampaignRecipientStatus,
    extra: { messageId?: string; error?: string } = {},
  ): Promise<void> {
    await this.deps.db
      .update(campaignRecipients)
      .set({
        status,
        messageId: extra.messageId ?? null,
        error: extra.error ?? null,
        sentAt: status === 'SENT' ? new Date() : undefined,
        updatedAt: new Date(),
      })
      .where(and(tenantWhere(campaignRecipients, scope), eq(campaignRecipients.id, id)));
  }

  private async countPending(scope: TenantScope, campaignId: string): Promise<number> {
    const [row] = await this.deps.db
      .select({ value: sql<number>`count(*)::int` })
      .from(campaignRecipients)
      .where(
        and(
          tenantWhere(campaignRecipients, scope),
          eq(campaignRecipients.campaignId, campaignId),
          eq(campaignRecipients.status, 'PENDING'),
        ),
      );
    return row?.value ?? 0;
  }

  private async openBatch(scope: TenantScope, campaignId: string, name: string): Promise<string> {
    const [row] = await this.deps.db
      .insert(messageBatches)
      .values({
        tenantId: scope.tenantId,
        subTenantId: scope.subTenantId ?? null,
        campaignId,
        name: `Campaign: ${name}`,
        status: 'QUEUED',
      })
      .returning({ id: messageBatches.id });
    return row!.id;
  }

  private async currentBatch(scope: TenantScope, campaignId: string): Promise<string> {
    const [row] = await this.deps.db
      .select({ id: messageBatches.id })
      .from(messageBatches)
      .where(and(tenantWhere(messageBatches, scope), eq(messageBatches.campaignId, campaignId)))
      .orderBy(sql`${messageBatches.createdAt} DESC`)
      .limit(1);
    if (!row) throw new NotFoundError(`Campaign '${campaignId}' has no batch`);
    return row.id;
  }

  private async setStatus(
    scope: TenantScope,
    campaignId: string,
    status: CampaignStatus,
  ): Promise<void> {
    await this.deps.db
      .update(campaigns)
      .set({ status, updatedAt: new Date() })
      .where(and(tenantWhere(campaigns, scope), eq(campaigns.id, campaignId)));
  }

  private async playbookByKey(scope: TenantScope, key: string) {
    const [row] = await this.deps.db
      .select({ id: playbooks.id, key: playbooks.key })
      .from(playbooks)
      .where(and(tenantWhere(playbooks, scope), eq(playbooks.key, key)))
      .limit(1);
    if (!row) throw new NotFoundError(`Playbook '${key}' is not installed for this tenant`);
    return row;
  }
}

/** A run result becomes the recipient's state. One place, so it cannot drift. */
function mapStatus(result: PlaybookRunResult): CampaignRecipientStatus {
  switch (result.status) {
    case 'SENT':
      return 'SENT';
    case 'QUEUED':
      return 'QUEUED';
    case 'PENDING_APPROVAL':
      return 'PENDING_APPROVAL';
    case 'SUPPRESSED':
      return 'SUPPRESSED';
    case 'SKIPPED':
      return 'SKIPPED';
    case 'FAILED':
    default:
      return 'FAILED';
  }
}

